const strings = {
    delivery:'Delivery in',
    time:'10 minuts',
    snow:'Snow',
    noticeheading:' It’s too cold outside',
    noticetext:'Our delivery partners may take longer to reach you. Don’t worry!',
    grocery:'Grocery & Kitchen',
    best:'Bestsellers',
    homestyle:'Home & Lifestyle',
    snacks:'Snacks & Drinks',
    sweets:'Search "sweets"',
    milk :'Search "milk"',
    aata:'Search "ata,dal,coke"',
    chips:'Search "chips"',
    pooja:'Search "pooza thali"',
    hello:'Hello',
    hash:'#',
    x:'X',
    available:'Available',
    delivered:'Delivered',
    rupay:'₹',
    zero:'.0',
    total:'TOTAL',
    add:'ADD',
    mobile:'+91',
    bottomlogin:'By Continung, you agree to our Terms of Service & Privacy Policy',
    item:'ITEM',
    next:'Next',
    deliverytime:'8 MINS',
    backtotop:'Back to Top',
    noorder:'No Orders found yet!',
    deliverydetails:'Your delivery details',
    currentorderdetails:'Details of your current order',
    deliveryhome:'Delivery at Home',
    recievercontactnumber:"Receiver's contact no.",
    livemap:'LiveMap',
    order:'Order is',
    view:'View',
    deliveryin:'Delivey in 9 minutes',
    shipment:'Shipment of',
    items:'item',
    palcedorder:'Order Placed',
    deliverytohome:'Delivering to Home',
    coupons:'Use Coupons',
    cancelpolocy:'Cancellation Policy',
    canceltext:'Orders cannot be cancelled once packed for delivery,In case of unexpected delays,a refund will be provided, if applicable',
    youraccount:'Your Account',
    information:'YOUR INFORMATION',
    pastorder:'PAST ORDERS',
    last:"India's last minute app",
    login:'Log In or signup',

  };
  
  export default strings;